server:
  port: 9000
  context-path: /slothsandra

spring:
  freemarker:
    cache: false

slothsandra:
  slack-name: abctech
  time-zone: UTC+7

db:
  host: 127.0.0.1
  port: 9042
  keyspace-name: slothsandra